# MySQL (default setup).

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: redmine
  host: localhost
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: redmine
  host: localhost
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: redmine
  host: localhost
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock
